Add job for publishing to PyPI

diff --git a/.github/workflows/pypi-release.yaml b/.github/workflows/pypi-release.yaml
--- a/.github/workflows/pypi-release.yaml
+++ b/.github/workflows/pypi-release.yaml
@@ -12,8 +12,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
       - uses: actions/setup-python@v2
         name: Install Python
         with:
@@ -26,12 +24,22 @@ jobs:
 
       - name: Build tarball and wheels
         run: |
+          git clean -xdf
+          git restore -SW .
           python setup.py sdist bdist_wheel
           python -m pip wheel . -w dist --no-deps
 
       - name: Test the artifacts
         run: |
           python -m twine check dist/*
+          git describe
+          pwd
+          if [ -f dist/xarray-999.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
 
       - uses: actions/upload-artifact@v2
         with:
@@ -58,3 +66,21 @@ jobs:
       - name: Install built artifacts
         run: |
           python -m pip install dist/*.tar.gz
+
+  upload-to-pypi:
+    needs: build-artifacts
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
+    steps:
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
+
+      - name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@v1.4.2
+        with:
+          user: ${{ secrets.PYPI_USERNAME }}
+          password: ${{ secrets.PYPI_PASSWORD }}
+          skip_existing: true
+          verbose: true
